---
runtime: shiny
output: html_document
---

```{r setup, include=FALSE, echo= FALSE}
library(ggplot2)
library(dplyr)
library(stringr)
library(shiny)
library(readr)
library(plotly)
boxscores <- readRDS("data//boxscores.rds")
```


```{r echo=FALSE}
Player <- sort(unique(boxscores$player))
stats_text <- c("Rebounds", 
           "Assists", 
           "Fouls", 
           "Blocks",
           "Steals"
           )
stats_var <- c("Reb", 
           "Ast", 
           "Fls", 
           "Blks",
           "Stl"
           )
```


```{r echo= FALSE}
# Define UI for miles per gallon app

ui <- pageWithSidebar(
  
  # App title
  headerPanel("Player Information"),
  
  #select a season

  
  
  # Sidebar panel for inputs
  sidebarPanel(
      h4("Select a Season:"),
    numericInput("year",label=h6("Year"),value=2015,max=2018,min=2015),
      # Input: Selector for variable to plot against mpg
    h4("Select a Player:"),
      selectInput("id1", "Player Name:", 
                Player, selected = Player[1], multiple = TRUE),
      
      # Input: Selector for variable to plot against mpg
      selectInput("stat", "Stats:", 
                stats_text),
      
      textAreaInput("text", "Info", 
                value = "Explore and compare players' game statistics", rows = 2)
  ),

  # Main panel for displaying outputs
  mainPanel(
      # Output: Plot of the requested variable against mpg
      plotlyOutput("bball_plot", height = "auto", width = "auto")
  )
)


```

```{r echo=FALSE}
# Define server logic
server <- function(input, output) {
  
  # Generate a plot of the requested variable 
  output$bball_plot1 <- renderPlotly({
    
    index <- match(input$stat,stats_text)
    
    statistic <- boxscores %>% 
      filter(id %in% input$id1) %>%
      select(id, stats_var[index], player)
    p <- ggplot(statistic, aes(x=factor(id), y=unname(unlist(statistic[,2])), color=factor(id), group=factor(id), label1=player)) + 
      geom_boxplot(fill = "white", colour = "#3366FF") + 
      geom_jitter(width = 0.15, size = 0.75) + 
      xlab("Player ID") + 
      ylab(stats_text[index])+
      labs(color="Player")
    
    ggplotly(p, tooltip = c("label1", "label2", "y"))
  })
    
}
shinyApp(ui, server, options = list(height = 1080))
```